[package]
name = "minecraft-rust-server"
version = "0.0.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
naia-bevy-server = { version = "0.23.0", features = ["transport_webrtc"] }
bevy_app = { version = "0.14", default-features=false }
bevy_core = { version = "0.14", default-features=false }
bevy_ecs = { version = "0.14", default-features=false }
bevy_log = { version = "0.14", default-features=false }
bevy = "0.14.2"

